### ISSUE TITLE
set schedule for final weeks

### ISSUE THREAD

**Issue by afeld** [cuny-nytech/syllabus#30]
* line up speaker(s?)
* find time for @PeterBell to come talk about professional presence
    * have students bring in resume for review
* check if @dbrizan has other topics he would 
* cover JS + AJAX
* is April 27 still a good end date?
* startup visit?

**Comment by PeterBell** [comment]
Hey @afeld let's discuss calendars tonight - would love to come in and do this!!!

**Comment by afeld** [comment]
@PeterBell Sweet! You pick the day, sometime between now and the 27th – doesn't make any difference to us.

**Comment by PeterBell** [comment]
@afeld does it need to be a Monday? 13th in SF, 20th in DEN, 27th in New Orleans :( Monday May 4th I'm in NYC or I could do something that isn't a Monday. Really sorry :( Let me know . . .

**Comment by afeld** [comment]
You are CRAZY :laughing: :airplane: It's a small group, so we could probably make another day of the week work. We'll chat IRL.

**Comment by PeterBell** [comment]
Sounds like a plan. Sorry I’m “up in the air” :)

**Comment by afeld** [comment]
@PeterBell Want to throw out some dates?

**Comment by PeterBell** [comment]
@afeld is 2017 out of the question? :smile:  

I don't have a single free night in NYC this month :frowning: 

What's latest date we might be able to do this?

**Comment by afeld** [comment]
That's CRAZY. Anyway, the class officially ends April 27th...maybe we could do it over video? If not, don't stress about it.
